language: python
sudo: false

jobs:
  include:
    - stage: "travis-ci testing 2.7"
      os: linux
      python:
        - '2.7.16'
      install:
        - pip install -r requirements_dev.txt
      script:
        - "export LANG='en_US.UTF-8'"
        - "export LC_ALL='en_US.UTF-8'"
        - "PYTHONIOENCODING=UTF-8 PYTHONPATH=. python -m pytest -v -s --cov=<package-name> tests"

    # add more stages if needed.

    - stage: "travis-ci testing 3.7"
      os: linux
      python:
        - '3.7'
      install:
        - pip install -r requirements_dev.txt
      script:
        - "PYTHONPATH=. pytest -v -s --cov=<package-name> tests"
      after_success:
        - coveralls

    - stage: "pypi deployment"
      deploy:
        provider: pypi
        user: "__token__"
        password:
          secure: <create-pypi-token-and-secure-it-using-travis-before-adding-it>
        on:
          tags: true
      script: echo "Deployment Done..!"
