---
# configuration spec at https://github.com/actions/labeler/blob/master/README.md
weblinks/docs:
  - CHANGELOG.md
  - CONTRIBUTING.md
  - LICENSE
  - README.md
weblinks/tests:
  - tests/*
  - tox.ini
weblinks/code:
  - weblinks/*
weblinks/ci:
  - .github/workflows/*
  - .github/labels/*
weblinks/settings:
  - setup.py
  - tox.ini
  - .gitignore
weblinks/pip:
  - requirements.txt
  - requirements_dev.txt
  - Pipfile
