---
name: Pull request labeler
on:
  schedule:
    - cron: '30 16 * * 3'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: paulfantom/periodic-labeler@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          LABEL_MAPPINGS_FILE: .github/labels/labeler.yml